### PR TITLE
Feature/marp 463 multilingualism for website

### PR DESCRIPTION
**Pull request by phhung-axonivy**

### CODE REVIEW

**Comment by phhung-axonivy** [comment]
@ivy-sgi
Should we merge it to the master branch or keep working on this branch for the new market website?

**Comment by ivy-sgi** [comment]
Hi @phhung-axonivy ! Let's merge it. 
Are you aware of missing translations for meta.json?

**Comment by phhung-axonivy** [comment]
Hi @ivy-sgi 
I reviewed this pull request. There are some TODO (full upper case) texts.
Could you please translate these texts?

**Comment by ivy-sgi** [comment]
Hi @phhung-axonivy I do not see any TODOs in https://market-preview.ivy-cloud.com/ - I guess I made it now.

**Comment by phhung-axonivy** [comment]
Hi @ivy-sgi 
I found that we are still missing the translation for some items below.
- market/basic-workflow-ui/meta.json
- market/connector/microsoft365/toDo/meta.json
- market/demos/processing-valve/meta.json
- market/demos/quick-start-tutorial/meta.json
Could you please update it?

**Comment by ivy-sgi** [comment]
Hi @phhung-axonivy Did it.
I did not provide translations for processing-valve and quickstart turorial as they are not listed in the website anymore.

**Review by nqhoan-axonivy — APPROVED** [review]
LGTM

**Pull request merged**
