### PR TITLE
MARP-578 Release vertexai google

### PR DESCRIPTION
**Pull request by tvtphuc-axonivy**

### CODE REVIEW

**Comment by tvtphuc-axonivy** [comment]
Hi @ivy-sgi  , Can you help me to review it , and if you like another image .Please tell me to update it.

**Comment by ivy-sgi** [comment]
Hi @tvtphuc-axonivy ! I have re-organized the documentation a bit and I am now quite happy with it. What do you think?

**Comment by tvtphuc-axonivy** [comment]
> Hi @tvtphuc-axonivy ! I have re-organized the documentation a bit and I am now quite happy with it. What do you think?

Hi @ivy-sgi , that is great. I agree with this change. I will merge this after your approval.

**Comment by ivy-sgi** [comment]
@tvtphuc-axonivy Approved :)

**Pull request merged**
