### PR TITLE
MARP-1018 add logo and meta.json for RTF factory

### PR DESCRIPTION
**Pull request by tvtphuc-axonivy**
Hi @ivy-sgi , I am currently onboarding the new connector https://1ivy.atlassian.net/browse/MARP-1018 from Bruno.

I have updated the meta.json and the logo for this new utility.

Could you please review it and let me know if you prefer a different image? Feel free to suggest any changes to the name and description if you find them unreasonable.

Thanks a lot.

### CODE REVIEW

**Review by ivy-sgi — CHANGES_REQUESTED** [review]
Please adapt the meta.json with the German translation (and adapt the englisch version)
  {
      "locale": "en",
      "value": "The RTF Factory creates RTF documents that can be quickly and easily extended with process data and ivy macro functions."
    },




    {
      "locale": "de",
      "value": "Die RTF Factory erstellt RTF Dokumente, die im schnell und mühelos mit Prozessdaten und ivy-Makrofunktionen erweitert werden können."
    }

**Comment by tvtphuc-axonivy** [comment]
Hello @ivy-sgi , I have updated the meta.json as you suggested. Please help me to re-review it.
Thanks

**Comment by ivy-sgi** [comment]
Hi @tvtphuc-axonivy ! 
I am super sorry, there was an error in my German translation. Could you please use the following:

{
  "locale": "de",
  "value": "Die RTF Factory erstellt RTF Dokumente, die  schnell und mühelos mit Prozessdaten und ivy-Makrofunktionen erweitert werden können."
}

**Comment by tvtphuc-axonivy** [comment]
Hello @ivy-sgi , I have updated meta.json. Can you help me to check it again.
Thanks

**Pull request merged**
