### PR TITLE
change twitter-connector to x-connector

### PR DESCRIPTION
**Pull request by tutn-axonivy**

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
cool, thanks @tutn-axonivy

**Comment by tutn-axonivy** [comment]
Hi @ivy-rew, I see some failures in the Jenkins pipeline. Is it OK?

**Comment by ivy-rew** [comment]
> Hi @ivy-rew, I see some failures in the Jenkins pipeline. Is it OK?

yes, I've re-triggered the build ... seems to have been an early attempt to resolve the metadata from maven, while it was not yet released. all fine now :+1:

**Comment by tutn-axonivy** [comment]
Hi @ivy-rew, I still see this connector on market.axonivy.com is using the old maven information. I think it because it get from the market-cache. Could you help me check it?

**Pull request merged**
