### PR TITLE
Onboard for Mattermost connector

### PR DESCRIPTION
**Pull request by phhung-axonivy**

### CODE REVIEW

**Comment by phhung-axonivy** [comment]
Hi @andreasbalsiger @ivy-sgi 
Could you help me review this pull request and give me your feedback?

**Comment by ivy-sgi** [comment]
I have edited meta.json a litte bit - from my side this connector is cool and should be published.
@andreasbalsiger Fine for you also?

**Comment by andreasbalsiger** [comment]
Yes... I like it... can someone do the merge? in the past, I was never the master of hitting the merge button 🥇

**Review by andreasbalsiger — COMMENTED** [review]
go

**Pull request merged**
